import { NextPage } from 'next'
import Head from 'next/head'

import { Gallery } from '../../components/Sections'

const Partners: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Together we can do more.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto mt-9 mb-24 flex max-w-[1142px] flex-col gap-24">
        <Gallery />
      </main>
    </div>
  )
}

export default Partners
