import { NextPage } from 'next'
import Head from 'next/head'

import { Differences, Education, Gallery, OurMission } from '../../components/Sections'

const AboutUs: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Наша миссия - помогать всем и каждому!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto mt-9 mb-24 flex max-w-[1142px] flex-col gap-24">
        <OurMission text="second" image="teacher" />
        <Differences />
        <Education />
        <Gallery />
      </main>
    </div>
  )
}

export default AboutUs
