import type { NextPage } from 'next'
import Head from 'next/head'

import {
  AboutUs,
  Admission,
  ContactUs,
  Cooperate,
  Differences,
  Experience,
  Hero,
  Introduction,
  News,
  OurMission,
  Reviews,
  Safety,
} from '../components/Sections'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Школа “Bek” future education</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Introduction />
        <div className="container mx-auto my-12 flex flex-col gap-12 px-6 md:my-24 md:gap-24 md:px-0">
          <Hero />
          <OurMission text="first" image="pupil" />
          <Differences />
          <AboutUs />
          <Safety />
          <Experience />
          <Cooperate />
          <Admission />
          <Reviews />
          <News />
          <ContactUs />
        </div>
      </main>
    </div>
  )
}

export default Home
